version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: npm install && npm start
  test:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: npm install && node index.js
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
